### ISSUE TITLE
Problem while trying to write to KMongo

### ISSUE THREAD

**Issue by ivan-brko** [jershell/kbson#14]
Hi,

I am new to Kotlin and its ecosystem, so I don't know if this bug is related to this repository or KMongo (or kotlix.serialization). 

There is a minimal repro [here](https://github.com/ivan-brko/KMongoIssueRepro).

The problem is following:

I have the following data class which is in a file I cannot edit:
```
data class User(
    val username: String,
    val email: String,
    val firstName: String,
    val lastName: String,
    val password: String,
    val role: Role,
    val createdAt: LocalDateTime,
    val updatedAt: LocalDateTime
)
```
So, in my file I create a serializer for it like this:

```
@Serializer(forClass = User::class)
object UserSerializer {}
```

Now, everything seems to work OK when deserializing the data, however when KMongo tries to serialize it and send it to DB, I get a nasty java exception stack with the following message:

> Exception in thread "main" java.lang.IndexOutOfBoundsException: User descriptor has only 8 elements, index: 0
> - at kotlinx.serialization.internal.PluginGeneratedSerialDescriptor.getElementDescriptor(PluginGeneratedSerialDescriptor.kt:62)
> - at com.**github.jershell.kbson.BsonEncoder**.encodeElement(BsonEncoder.kt:109)
> - ...

After going through code, I found that in file PluginGeneratedSerialDescriptor.kt there is an overriden fun getElementDescriptor in which property generatedSerializer is trying to get accessed, but it is null and this causes the exception.

Does anyone know if this is a bug, or I'm doing something wrong here? If it has nothing do to with this repository, sorry for bothering you, I'll ask in kotlinx.serialization.

Thanks!

**Comment by zigzago** [comment]
Thank you for reporting.

 This is a bug in kbson & kmongo with "@Serializer annotation". Try KMongo 4.0.1-SNAPSHOT (using https://oss.sonatype.org/content/repositories/snapshots repo) that contains the bug fix. Look at this unit test: https://github.com/Litote/kmongo/blob/master/kmongo-serialization-mapping/src/test/kotlin/ExternalSerializerTest.kt#L52

I will port the fix to kbson later.

**Comment by ivan-brko** [comment]
Thanks for the answer, that was fast!

Should I close this issue or do you want to close it when you port the fix?

**Comment by zigzago** [comment]
I will close the issue when kbson will be fixed, thank you
