### ISSUE TITLE
Polymorphism is not supported

### ISSUE THREAD

**Issue by zigzago** [jershell/kbson#3]
I get this stacktrace when I try to serialize a inherited class (as described here https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md )

java.lang.ClassCastException: kotlinx.serialization.UnionKind$POLYMORPHIC cannot be cast to kotlinx.serialization.StructureKind

	at com.github.jershell.kbson.BsonEncoder.beginStructure(BsonEncoder.kt:28)
	at kotlinx.serialization.PolymorphicSerializer.serialize(Polymorphic.kt:87)

**Comment by jershell** [comment]
Nice, I got it. Will try to implement during week

**Comment by jershell** [comment]
https://github.com/Litote/kmongo/issues/104

**Comment by jershell** [comment]
I implemented it like in kotlinx.serialization.json by "classDiscriminator"(name of the class descriptor property in polymorphic serialization.)

You can look at it in tests
parsePolymorphismSealed()
stringifyPolymorphismSealed()
parsePolymorphismComplexHierarchies()
stringifyPolymorphismComplexHierarchies()
parsePolymorphism()
stringifyPolymorphism()
I take this from their readme https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md

**Comment by zigzago** [comment]
Thank you
