### ISSUE TITLE
Add kbson to maven central

### ISSUE THREAD

**Issue by zigzago** [jershell/kbson#8]
kmongo is in maven central. When using kmongo-serialization, users need to add the bintray repository...

**Comment by jershell** [comment]
WIP

**Comment by jershell** [comment]
https://issues.sonatype.org/browse/OSSRH-52456

**Comment by jershell** [comment]
I think i did it, but need check that https://repo.maven.apache.org/maven2/com/github/jershell/kbson/  is avalible
